### ISSUE TITLE
Segfault in running segmentation.

### ISSUE THREAD

**Issue by yamikumo-DSD** [chenhcs/scResolve#5]
I got segmentation fault when running scResolve's segmentation in the tutorial pipeline provided.

The actual command I ran is
```
scresolve segmentation tutorial.toml --count ./tutorial/segment_input/section1.tsv --image ./tutorial/segment_input/section1.jpg --output_path ./results
```
, and the .toml file is like: 
```toml
[super_resolution_model]
network_depth = 6
network_width = 16
min_counts = 50

[super_resolution_expansion_strategy]
type = "DropAndSplit"
[super_resolution_expansion_strategy.DropAndSplit]
max_metagenes = 50

[super_resolution_optimization]
batch_size = 3
epochs = 100000
learning_rate = 0.0003
patch_size = 768

[super_resolution_analyses]
[super_resolution_analyses.metagenes]
type = "metagenes"
[super_resolution_analyses.metagenes.options]
method = "pca"

[super_resolution_analyses.gene_maps]
type = "gene_maps"
[super_resolution_analyses.gene_maps.options]
gene_regex = ".*"
predict_mean = false
writer = "tensor"

[super_resolution_backtrack]
backtrack = true
min_num_metagenes = 20

[segmentation]
ws_otsu_classes = 4
bg_th = 100
epochs = 1 # I lowered the value for test purpose.
patch_size = 1000

[slides]
[slides.section1]
data = "path_to_h5"
[slides.section1.covariates]
section = 1
```
I got an error after several cycles, which is like:
```
(after several patches successfully processed)

Prepare data for neural network...
975 970 9000 9070
[2025-03-27 11:12:32,655] _ WARNING : ImplicitModificationWarning (/opt/miniconda3/envs/scresolve/lib/python3.8/site-packages/anndata/_core/anndata.py:121): Transforming to str index.
[2025-03-27 11:12:32,692] _ WARNING : ImplicitModificationWarning (/opt/miniconda3/envs/scresolve/lib/python3.8/site-packages/anndata/_core/anndata.py:121): Transforming to str index.
Segmentation fault (core dumped)
```
What do you guys the reason will be?
I found an issue of SCS, which scResolve based on, stating a problem similar to my case (https://github.com/chenhcs/SCS/issues/8).

Anyway, please tell me if anyone met this problem or fix it.
Thank you.
